In [0]:
import numpy as np
import sys

For simulation purposes, we set the dimension for the matrices to be 3.

In [0]:
dimension = 3

First we want to construct the matrices. Since the value of X is dependent on 'a', we will initialize that value in our code. For simulation purposes we will take 'a' to be 2. As stated in the pdf, we can write X^a as a combination of kets where each ket is a function of 'a' modulo 'd'. (d is dimension)
Z^b on the other hand, is simply a diagonal matrix where each entry along the diagonal is (w^b). For the purpose of proving orthoganility, we can ignore the power of b.

In [18]:
a = 2
# initiaizing Z
Z = np.identity(dimension)

print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Next, we will calculate the respective kets of X

In [7]:
ket = [0]*(dimension)
for i in range(0, dimension):
  ket[i] = (a+i) % dimension
print(ket)

[2, 0, 1]


Each entry in the ket array indicates the number of the ket in the X matrix. We will use that to initialize the X matrix

In [12]:
X = np.zeros((dimension, dimension))


index = 0
for i in ket:
  X[index][i] = 1
  index += 1

X = np.transpose(X)
print(X)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


Now that our matrices are ready, we only need to show that all of the vectors have dot product equal to 0.

In [19]:
prod = 0
for i in range(0, dimension):
  x = X[i][i]
  z = Z[i][i]
  prod = prod + (x*z)
  
if prod == 0:
  print("X and Z are orthogonal")
else:
  print("X and Z are not orthogonal")

X and Z are orthogonal
